import { RecruitPostType } from '@/constants/types/recruit';

export const RecruitPostDummyData: RecruitPostType[] = [
  {
    title: 'SSC1',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC2',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC3',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC4',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC5',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC6',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC7',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC8',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC9',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
];

export const ApplyDummyData = [
  {
    name: '영어회화 동아리1',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
  {
    name: '영어회화 동아리2',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '합격',
  },
  {
    name: '영어회화 동아리3',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
  {
    name: '영어회화 동아리4',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
];

export const ApplyDocumentData = [
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
];

export const userDummyData = [
  'user',
  '배현서',
  'qogustj@naver.com',
  '학생',
  24,
];

export const organizationDummyData = [
  'organization',
  'SSC',
  '축구동아리',
  '배현서',
  'qogustj@naver.com',
  '숭실대학교',
];
