import { RecruitPostType } from '@/constants/types/recruit';

export const RecruitPostDummyData: RecruitPostType[] = [
  {
    title: 'OnTheFloor',
    introduce:
      '영화 콘텐츠 제작 크루 <OnTheFloor>에서 함께 팟캐스트를 도전할 4기 멤버를 모집합니다!',
    organizationType: '동아리',
    target: '영화를 좋아하는 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content:
      '영화와 관련된 콘텐츠 활동들을 직접 기획하고 제작하며 자신만의 영화 스펙트럼을 확장시키는 크루입니다. 영화를 사랑하는 사람들, 미래에 영화계에 종사하고 싶은 사람들, 영화 관련 뉴미디어 콘텐츠에 도전하고 싶은 사람들이 모여 영화지식과 시야를 넓히고 영화계 취업 정보 공유 및 스펙 형성에도 서로 도움을 주는 커뮤니티로 성장하고자 합니다. 본 크루는 팟캐스트를 기본 활동으로 전제를 두고 있으며 주된 동아리 활동 또한 팟캐스트 분야에 집중할 예정입니다. 그 이후의 활동은 차후 기획 부서를 수립하여 대학 영화 신문, 단편 영화 제작 등을 시도할 계획입니다. 실제로 저희 동아리는 양주 배리어프리 영화제에 모든 동아리원이 온라인 서포터즈로 참여하는 등, 여러 영화제들과의 협업 활동을 이어가고 있습니다. 또한 잡지 제작 프로젝트와 협업을 진행하여 대학생 영화 잡지 <MAYPOLE>의 창간호와 2호 출판에 도움을 주었습니다.(*<MAYPOLE> 잡지 프로젝트는 동아리와 별개의 프로젝트로, 프로젝트에 참여하게 되는 인원은 동아리 활동에 지장이 없어야만 합니다. 잡지 프로젝트와는 인원 모집 및 출판물 홍보에 도움을 주고 있습니다. <MAYPOLE>의 프로젝트 인원 모집은 저희 OnTheFloor 인원을 우선적으로 모집하여 진행합니다. 특히 3기부터는 인천 미추홀구에 위치한 복합 영화 문화 공간 ‘영화공간주안’과의 협업 활동을 진행하게 되었습니다. 영화공간주안과 관련된 여러가지 홍보 컨텐츠들을 제작할 뿐만 아니라, 영화공간주안에서 열리는 독립영화 GV를 기획해서 진행을 직접 맡거나 협업 굿즈를 제작하는 등, 여러 행사들에 저희 동아리원들이 직접 참여하여 다양한 활동을 하고 있습니다. 이러한 유익한 활동 내용을 인정받아, 본 동아리는 아웃캠퍼스가 주관하는 제 10회 명품동아리 공모전에서 TOP 10 동아리에 선정되기도 하였습니다.',
    recruitURL:
      'https://docs.google.com/forms/d/e/1FAIpQLSfKex69vMhjL3rv0hQX_UaQrJvh3NMgWkFhTIx7ihoTjd1WIg/viewform?vc=0&c=0&w=1&flr=0',
    thumbnailImg: '/dummy1.jpg',
  },
  {
    title: 'SSC2',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC3',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC4',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC5',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC6',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC7',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC8',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC9',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
];

export const ApplyDummyData = [
  {
    name: '영어회화 동아리1',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
  {
    name: '영어회화 동아리2',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '합격',
  },
  {
    name: '영어회화 동아리3',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
  {
    name: '영어회화 동아리4',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
    type: '동아리',
    result: '지원완료',
  },
];

export const ApplyDocumentData = [
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
];

export const ApplicantData = [
  {
    name: '배현서',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    name: '배현서',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    name: '배현서',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
  {
    name: '배현서',
    paper: '숭실대 소프트웨어학부 배현서 지원서',
    date: '2023.04.11',
  },
];

export const userDummyData = [
  'user',
  '배현서',
  'qogustj@naver.com',
  '학생',
  24,
];

export const organizationDummyData = [
  'organization',
  'SSC',
  '축구동아리',
  '배현서',
  'qogustj@naver.com',
  '숭실대학교',
];
