export const RecruitPostDummyData: RecruitPostType[] = [
  {
    title: 'SSC1',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC2',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC3',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC4',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC5',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
  {
    title: 'SSC6',
    introduce: '숭실대 축구 동아리입니다. 숭실대 축구 동아리입니다.',
    organizationType: '동아리',
    target: '축구 잘하는 사람 누구나',
    recruitStartDate: '2023-05-25',
    recruitEndDate: '2023-06-01',
    activityStartDate: '2023-07-01',
    acitivityEndDate: '2024-07-01',
    recruitCount: 30,
    content: '',
    recruitURL: '/',
    thumbnailImg: '/dummy-thumbnail.jpg',
  },
];
